/**
 * Verifies that the dependency tree contains no copyleft licence, then generates
 * THIRD-PARTY-NOTICES.md.
 *
 * Project decision (PLAN.md §2.1): only permissive licences are admitted. Any unknown
 * licence counts as a violation — an `UNKNOWN` must be resolved by hand, not ignored.
 *
 * Usage: npm run check:licenses
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ALLOWED = new Set([
  '0BSD',
  'Apache-2.0',
  'BlueOak-1.0.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'CC0-1.0',
  'CC-BY-4.0',
  'ISC',
  'MIT',
  'MIT-0',
  'OFL-1.1',
  'Python-2.0',
  'Unlicense',
  'WTFPL',
]);

/** Explicitly rejected licences — any match fails the check outright. */
const FORBIDDEN = /\b(A?GPL|LGPL|SSPL|BUSL|CDDL|EPL|MPL|CPAL|OSL)\b/i;

interface Pkg {
  name?: string;
  version?: string;
  license?: string | { type?: string };
  licenses?: Array<{ type?: string }> | string;
  private?: boolean;
}

interface Entry {
  name: string;
  version: string;
  license: string;
  path: string;
}

/** Normalises the `license` field, which has three historical shapes in npm. */
function readLicense(pkg: Pkg): string {
  if (typeof pkg.license === 'string') return pkg.license;
  if (pkg.license && typeof pkg.license === 'object' && pkg.license.type) return pkg.license.type;
  if (Array.isArray(pkg.licenses)) {
    const types = pkg.licenses.map((l) => l.type).filter((t): t is string => Boolean(t));
    if (types.length > 0) return types.join(' OR ');
  }
  if (typeof pkg.licenses === 'string') return pkg.licenses;
  return 'UNKNOWN';
}

/**
 * An SPDX expression is accepted when:
 *  - it is an OR with at least one permissive branch (we can pick that branch);
 *  - it is an AND whose every branch is permissive.
 */
function isAllowed(expr: string): boolean {
  const cleaned = expr.replace(/[()]/g, ' ').trim();
  if (ALLOWED.has(cleaned)) return true;

  if (/\bOR\b/i.test(cleaned)) {
    return cleaned.split(/\bOR\b/i).some((branch) => isAllowed(branch.trim()));
  }
  if (/\bAND\b/i.test(cleaned)) {
    return cleaned.split(/\bAND\b/i).every((branch) => isAllowed(branch.trim()));
  }
  return ALLOWED.has(cleaned.replace(/\+$/, ''));
}

/** Walks node_modules, including @foo/bar scopes and nested node_modules. */
function collect(dir: string, out: Map<string, Entry>): void {
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    return;
  }

  for (const name of names) {
    if (name === '.bin' || name === '.cache') continue;
    const full = join(dir, name);

    if (name.startsWith('@')) {
      collect(full, out);
      continue;
    }

    const manifest = join(full, 'package.json');
    let pkg: Pkg;
    try {
      if (!statSync(manifest).isFile()) continue;
      pkg = JSON.parse(readFileSync(manifest, 'utf8')) as Pkg;
    } catch {
      continue;
    }

    if (pkg.name && pkg.version) {
      const key = `${pkg.name}@${pkg.version}`;
      if (!out.has(key)) {
        out.set(key, {
          name: pkg.name,
          version: pkg.version,
          license: readLicense(pkg),
          path: full,
        });
      }
    }

    collect(join(full, 'node_modules'), out);
  }
}

const root = resolve(import.meta.dirname, '..');
const packages = new Map<string, Entry>();
collect(join(root, 'node_modules'), packages);

if (packages.size === 0) {
  console.error('No dependency found — run `npm install` first.');
  process.exit(1);
}

const sorted = [...packages.values()].sort((a, b) => a.name.localeCompare(b.name));
const violations = sorted.filter((e) => FORBIDDEN.test(e.license) || !isAllowed(e.license));

const byLicense = new Map<string, number>();
for (const entry of sorted) byLicense.set(entry.license, (byLicense.get(entry.license) ?? 0) + 1);

console.log(`${sorted.length} packages analysed.\n`);
console.log('Licence breakdown:');
for (const [license, count] of [...byLicense.entries()].sort((a, b) => b[1] - a[1])) {
  console.log(`  ${String(count).padStart(4)}  ${license}`);
}

if (violations.length > 0) {
  console.error(`\n✗ ${violations.length} disallowed licence(s):\n`);
  for (const v of violations) {
    console.error(`  ${v.name}@${v.version} — ${v.license}`);
  }
  console.error('\nAllowlist: ' + [...ALLOWED].sort().join(', '));
  console.error('See PLAN.md §2.1. Remove the dependency or resolve the licence explicitly.');
  process.exit(1);
}

const notices = [
  '# Third-party notices',
  '',
  'Quantum Draft builds on the packages below. Generated by `npm run check:licenses`.',
  '',
  '| Package | Version | Licence |',
  '|---|---|---|',
  ...sorted.map((e) => `| ${e.name} | ${e.version} | ${e.license} |`),
  '',
];
writeFileSync(join(root, 'THIRD-PARTY-NOTICES.md'), notices.join('\n'), 'utf8');

console.log('\n✓ All licences are permissive. THIRD-PARTY-NOTICES.md regenerated.');
